[package]
name = "mq"
version = "0.1.12"
edition = "2024"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bracket-lib = { version = "0.8.7", features = ["serde"] }
rltk = "0.8.7"
ron = "0.12.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
specs = { version = "0.20.0", features = ["serde"] }
specs-derive = "0.4.1"

